/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

version = "v0.0.3"
plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java`
     id("org.openstreetmap.josm") version "0.8.2"
}

base.archivesBaseName = "webp"
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    packIntoJar("org.sejda.imageio:webp-imageio:0.1.6")
}

josm {
  pluginName = "webp"
  josmCompileVersion = "18463"
  packIntoJarFileFilter = { it.exclude("META-INF/maven/*").exclude("META-INF/MANIFEST.MF") }
  manifest {
    description = "Adds support for webp image handling"
    mainClass = "org.openstreetmap.josm.plugins.webp.WebpPlugin"
    minJosmVersion = "18463"
    author = "ramSeraph"
    includeLinksToGithubReleases = true
    loadEarly = true
    website = uri("https://github.com/ramSeraph/josm-webp-plugin").toURL()
  }
  github {
      repositoryName = "josm-webp-plugin"
      repositoryOwner = "ramSeraph"
      targetCommitish = "main"
  }
}

